# Generated by Django 3.2.4 on 2021-07-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210704_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
