# Generated by Django 3.2.4 on 2021-07-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignupUser',
            new_name='Users',
        ),
    ]
