# Generated by Django 3.2.4 on 2021-07-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_rename_signupuser_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
