# Generated by Django 3.2.4 on 2021-07-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
