# Generated by Django 3.2.4 on 2021-07-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
