# Generated by Django 3.2.4 on 2021-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_signupuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
