# Generated by Django 3.2.4 on 2021-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_signupuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
