# Generated by Django 3.2.4 on 2021-07-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_signupuser_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupUser',
        ),
    ]
